### ISSUE TITLE
Windows installer is not self-containing

### ISSUE THREAD

**Issue by horvathp** [kalmant/gndapp#12]
![bug1](https://user-images.githubusercontent.com/4051763/71542825-88b4a100-296b-11ea-8317-3adcb0d18ced.png)

When trying to start tracking...

**Comment by horvathp** [comment]
It was missing the *32 bit* VC2015 runtime. I'm wondering why does it need the VC runtime, and why a 32 bit runtime on a 64 bit OS.

**Comment by kalmant** [comment]
The installer itself is not part of this repository, so I'm afraid this issue is out of scope here.
As a sidenote, the reason it requires 32 bit runtime is the fact that the windows installer is a 32 bit installer.

**Comment by horvathp** [comment]
This error pops up after successful installation, as I clearly described above, when one clicks "Track the satellite".

**Comment by kalmant** [comment]
The installer itself only copies files, it does not check whether things actually work.
