### ISSUE TITLE
Azimuth, Elevation angles visibility

### ISSUE THREAD

**Issue by therman89** [kalmant/gndapp#5]
The Az, El angles are written with quite small font sizes. My idea is to increase those and move it to the right side of the window, there is enough space for them. See attachment for visual representation.
Maybe it's worth including the frequency as well.

![GND_app_idea](https://user-images.githubusercontent.com/10553343/71245166-6fc94180-2314-11ea-8089-2fedb24595c8.png)

**Comment by kalmant** [comment]
Thank you for the idea! It's been implemented in #7.
